import { ArrowRight, Globe } from 'lucide-react';
import { useApp } from '../App';
import { Button } from '../components/ui/Button';
import { PageHero } from '../components/ui/PageHero';
import { SectionHeading } from '../components/ui/SectionHeading';

export default function About() {
  const { setPage, t } = useApp();
  const a = t.about;
  const p = t.aboutPage;
  return <div>
    <PageHero eyebrow={p.hero.label} title={p.hero.title} description={p.hero.sub} />
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20"><div className="grid gap-5 lg:grid-cols-2">{[{ title: a.mission.title, description: a.mission.desc }, { title: a.vision.title, description: a.vision.desc }].map(item => <article key={item.title} className="rounded-[var(--radius-lg)] border p-8" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}><p className="text-xs font-bold uppercase tracking-[0.14em]" style={{ color: 'var(--blue)' }}>{item.title}</p><p className="mt-5 text-lg font-bold leading-relaxed" style={{ color: 'var(--text)' }}>{item.description}</p></article>)}</div></section>
    <section className="border-y" style={{ background: 'var(--bg-2)', borderColor: 'var(--border)' }}><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20"><SectionHeading eyebrow={p.hero.label} title={a.values.title} description="" /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{a.values.items.map((value, index) => <article key={value.title} className="rounded-[var(--radius-lg)] border p-6" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}><span className="text-sm font-extrabold" style={{ color: 'var(--blue)' }}>{String(index + 1).padStart(2, '0')}</span><h3 className="mt-5 text-lg font-extrabold" style={{ color: 'var(--text)' }}>{value.title}</h3><p className="mt-3 text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{value.desc}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20"><SectionHeading eyebrow={p.hero.label} title={p.principles.title} description={p.principles.sub} /><div className="mt-10 grid gap-x-14 gap-y-8 lg:grid-cols-2">{p.principles.items.map(item => <article key={item.title}><h3 className="text-lg font-extrabold" style={{ color: 'var(--text)' }}>{item.title}</h3><p className="mt-2 text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{item.desc}</p></article>)}</div></section>
    <section className="border-y" style={{ background: 'var(--bg-2)', borderColor: 'var(--border)' }}><div className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20"><SectionHeading eyebrow={p.hero.label} title={p.process.title} description="" /><ol className="mt-10">{p.process.steps.map(step => <li key={step.num} className="grid gap-4 border-b py-6 last:border-b-0 lg:grid-cols-4" style={{ borderColor: 'var(--border)' }}><span className="text-sm font-extrabold" style={{ color: 'var(--blue)' }}>{step.num}</span><div className="lg:col-span-3"><h3 className="text-lg font-extrabold" style={{ color: 'var(--text)' }}>{step.title}</h3><p className="mt-2 text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{step.desc}</p></div></li>)}</ol></div></section>
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow={p.globalLabel} title={a.global.title} description={a.global.desc} /><Button variant="ghost" className="mt-8" onClick={() => setPage('contact')}>{p.getInTouch}<ArrowRight size={16} /></Button></div><div className="grid grid-cols-2 gap-4">{p.stats.map(stat => <div key={stat.label} className="rounded-[var(--radius-lg)] border p-6 text-center" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}><Globe size={18} className="mx-auto" style={{ color: 'var(--blue)' }} /><p className="mt-3 text-2xl font-extrabold" style={{ color: 'var(--text)' }}>{stat.value}</p><p className="mt-1 text-xs" style={{ color: 'var(--text-muted)' }}>{stat.label}</p></div>)}</div></div></section>
  </div>;
}
