import { useEffect, useRef, useState, type CSSProperties, type MouseEvent, type ReactNode } from 'react';
import { motion, useInView, useReducedMotion } from 'framer-motion';
import { Disclosure } from '../components/ui/Disclosure';
import { ArrowRight, Brain, Building2, Zap, Cloud, Globe, CheckCircle2, ChevronDown, Cpu } from 'lucide-react';
import { useApp } from '../App';
import { pagePath } from '../router';

const fadeUp = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.25, 0.1, 0.25, 1] } } };
const stagger = { show: { transition: { staggerChildren: 0.1 } } };
const TECHS = ['OpenAI', 'Microsoft', 'Amazon Web Services', 'Google Cloud', 'Microsoft Azure', 'Docker', 'Kubernetes', 'Cloudflare', 'Vercel', 'Supabase', 'Stripe', 'Odoo', 'ERPNext', 'PostgreSQL', 'Redis', 'Terraform'];
const SOLUTION_ICONS = [Brain, Building2, Zap, Cloud];
const PRODUCT_ICONS = [Brain, Building2, Globe, Zap, CheckCircle2, Sparkle];

function Section({ children, className = '' }: { children: ReactNode; className?: string }) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: '-80px' });
  const reducedMotion = useReducedMotion();
  return <motion.div ref={ref} variants={reducedMotion ? undefined : stagger} initial={reducedMotion ? false : 'hidden'} animate={reducedMotion ? undefined : (inView ? 'show' : 'hidden')} className={className}>{children}</motion.div>;
}

function Counter({ target, suffix = '' }: { target: number; suffix?: string }) {
  const [value, setValue] = useState(0);
  const ref = useRef(null);
  const reduced = useReducedMotion();
  const inView = useInView(ref, { once: true });
  useEffect(() => {
    if (!inView || reduced) return;
    let start = 0;
    const step = (time: number) => {
      if (!start) start = time;
      const progress = Math.min((time - start) / 1400, 1);
      setValue(Math.floor(progress * target));
      if (progress < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [inView, reduced, target]);
  return <span ref={ref}>{reduced ? target : value}{suffix}</span>;
}

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return <Disclosure id={q} title={q} open={open} onToggle={() => setOpen(value => !value)}><p className="text-[15px] leading-relaxed" style={{ color: 'var(--text-3)' }}>{a}</p></Disclosure>;
}

function SystemMap() {
  return <div className="hero-system-map" aria-hidden="true"><svg viewBox="0 0 620 430" fill="none"><path className="hero-system-path" d="M84 126H226L314 214H522" /><path className="hero-system-path" d="M154 318H242L314 214V70H458" /><path className="hero-system-path hero-system-path--soft" d="M84 126L154 318M458 70L522 214" /><circle className="hero-system-node" cx="84" cy="126" r="12" /><circle className="hero-system-node" cx="154" cy="318" r="12" /><circle className="hero-system-node hero-system-node--core" cx="314" cy="214" r="24" /><circle className="hero-system-node" cx="458" cy="70" r="12" /><circle className="hero-system-node" cx="522" cy="214" r="12" /><circle className="hero-system-pulse" cx="314" cy="214" r="46" /></svg></div>;
}

export default function Home() {
  const { t, setPage, openAI } = useApp();
  const reducedMotion = useReducedMotion();
  const navigate = (page: 'solutions' | 'products') => (event: MouseEvent<HTMLAnchorElement>) => { event.preventDefault(); setPage(page); };

  return <div className="flex flex-col">
    <section data-home-section="hero" className="relative min-h-screen flex flex-col justify-center pt-24 pb-24 overflow-hidden" style={{ background: 'var(--bg)' }}>
      <div className="absolute inset-0 pointer-events-none" style={{ backgroundImage: 'linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px)', backgroundSize: '80px 80px', opacity: 0.4 }} />
      <div className="absolute top-1/4 right-0 w-[600px] h-[600px] pointer-events-none" style={{ background: 'radial-gradient(ellipse at 80% 40%, rgba(21,101,242,0.08) 0%, transparent 70%)' }} />
      <SystemMap />
      <div className="max-w-7xl mx-auto px-6 lg:px-8 relative w-full"><motion.div initial={reducedMotion ? false : 'hidden'} animate={reducedMotion ? undefined : 'show'} variants={reducedMotion ? undefined : stagger}>
        <motion.p variants={fadeUp} className="text-[12px] font-700 uppercase tracking-widest mb-8" style={{ color: 'var(--blue)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.hero.label}</motion.p>
        <motion.h1 variants={fadeUp} className="font-800 leading-none mb-6" style={{ fontWeight: 800, fontSize: 'clamp(48px, 8vw, 88px)', letterSpacing: '-0.03em', color: 'var(--text)', maxWidth: 900 }}>{t.hero.headline1} <span className="relative inline-block" style={{ color: 'var(--blue)' }}>{t.hero.headline2}<span className="absolute bottom-0 left-0 right-0 h-[3px] rounded-full" style={{ background: 'var(--blue)', bottom: '-4px' }} /></span></motion.h1>
        <motion.p variants={fadeUp} className="text-[18px] leading-relaxed mb-10 max-w-2xl" style={{ color: 'var(--text-3)' }}>{t.hero.sub}</motion.p>
        <motion.div variants={fadeUp} className="flex flex-wrap gap-4"><button onClick={() => setPage('contact')} className="ui-focus-ring flex items-center gap-2 px-6 py-3.5 text-[15px] font-700 rounded-xl transition-all duration-200 group" style={{ background: 'var(--blue)', color: '#fff', fontWeight: 700 }}>{t.hero.cta1}<ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" /></button><button onClick={() => setPage('solutions')} className="ui-focus-ring px-6 py-3.5 text-[15px] font-700 rounded-xl border transition-all duration-200" style={{ color: 'var(--text)', borderColor: 'var(--border)', fontWeight: 700, background: 'transparent' }}>{t.hero.cta2}</button></motion.div>
        <motion.div variants={fadeUp} className="mt-16 grid grid-cols-3 gap-8 max-w-lg">{t.home.stats.map(({ value, suffix, label }) => <div key={label}><p className="text-[32px] font-800 leading-none mb-1" style={{ fontWeight: 800, color: 'var(--text)' }}><Counter target={value} suffix={suffix} /></p><p className="text-[13px]" style={{ color: 'var(--text-3)' }}>{label}</p></div>)}</motion.div>
      </motion.div></div>
      <motion.div initial={reducedMotion ? false : { opacity: 0 }} animate={{ opacity: 1 }} transition={reducedMotion ? { duration: 0 } : { delay: 1.5 }} className="absolute bottom-8 left-1/2 -translate-x-1/2" aria-hidden="true"><motion.div animate={reducedMotion ? undefined : { y: [0, 6, 0] }} transition={reducedMotion ? { duration: 0 } : { duration: 1.8, repeat: Infinity, ease: 'easeInOut' }} style={{ color: 'var(--text-4)' }}><ChevronDown size={18} /></motion.div></motion.div>
    </section>

    <section data-home-section="proof" style={{ borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)', background: 'var(--bg-2)', overflow: 'hidden', padding: '56px 0' }}>
      <div className="max-w-7xl mx-auto px-6 lg:px-8 mb-10 text-center"><p className="text-[12px] font-700 uppercase tracking-widest mb-3" style={{ color: 'var(--text-4)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.ecosystem.title}</p><p className="text-[16px]" style={{ color: 'var(--text-3)' }}>{t.ecosystem.sub}</p></div>
      <div style={{ overflow: 'hidden', position: 'relative' }}><div className="marquee-track flex items-center gap-12" style={{ width: 'max-content' }}>{[...TECHS, ...TECHS].map((tech, index) => <div key={tech + '-' + index} className="flex items-center gap-2 px-6 py-3 rounded-xl border whitespace-nowrap" style={{ background: 'var(--surface)', borderColor: 'var(--border)', color: 'var(--text-3)', fontSize: 14, fontWeight: 600, flexShrink: 0 }}><Cpu size={14} style={{ color: 'var(--blue)' }} />{tech}</div>)}</div><div className="absolute inset-y-0 left-0 w-24 pointer-events-none" style={{ background: 'linear-gradient(to right, var(--bg-2), transparent)' }} /><div className="absolute inset-y-0 right-0 w-24 pointer-events-none" style={{ background: 'linear-gradient(to left, var(--bg-2), transparent)' }} /></div>
      <div className="max-w-7xl mx-auto px-6 lg:px-8 pt-16 grid grid-cols-1 lg:grid-cols-[1.3fr_1fr] gap-10"><div><h2 className="text-[22px] font-800 mb-3" style={{ color: 'var(--text)', fontWeight: 800 }}>{t.industries.title}</h2><p className="text-[15px] leading-relaxed mb-6 max-w-2xl" style={{ color: 'var(--text-3)' }}>{t.home.industriesIntro}</p><div className="flex flex-wrap gap-2">{t.industries.items.map(industry => <span key={industry} className="px-3 py-2 rounded-lg text-[13px] font-600 border" style={{ color: 'var(--text-2)', background: 'var(--surface)', borderColor: 'var(--border)', fontWeight: 600 }}>{industry}</span>)}</div></div><div className="lg:border-l lg:pl-10" style={{ borderColor: 'var(--border)' }}><h2 className="text-[22px] font-800 mb-5" style={{ color: 'var(--text)', fontWeight: 800 }}>{t.home.partnershipTitle}</h2><div className="space-y-5">{t.why.items.slice(0, 2).map(item => <div key={item.num}><p className="text-[14px] font-700 mb-1" style={{ color: 'var(--text)', fontWeight: 700 }}>{item.title}</p><p className="text-[14px] leading-relaxed" style={{ color: 'var(--text-3)' }}>{item.desc}</p></div>)}</div></div></div>
    </section>

    <section data-home-section="outcomes" style={{ background: 'var(--bg-2)', borderBottom: '1px solid var(--border)' }}><div className="max-w-7xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="mb-16"><p className="text-[12px] font-700 uppercase tracking-widest mb-4" style={{ color: 'var(--blue)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.exampleSolutions.title}</p><h2 className="font-800 leading-tight max-w-xl" style={{ fontWeight: 800, fontSize: 'clamp(28px, 3.5vw, 40px)', letterSpacing: '-0.02em', color: 'var(--text)' }}>{t.exampleSolutions.sub}</h2></motion.div><div className="grid grid-cols-1 lg:grid-cols-3 gap-6">{t.exampleSolutions.items.map(item => <motion.div key={item.title} variants={fadeUp} className="p-8 rounded-2xl border flex flex-col" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}><span className="self-start text-[11px] font-700 uppercase tracking-widest px-3 py-1.5 rounded-full mb-6" style={{ color: 'var(--blue)', background: 'var(--blue-subtle)', letterSpacing: '0.1em', fontWeight: 700 }}>{item.label}</span><h3 className="text-[20px] font-700 mb-3" style={{ fontWeight: 700, color: 'var(--text)' }}>{item.title}</h3><p className="text-[14px] leading-relaxed mb-6 flex-1" style={{ color: 'var(--text-3)' }}>{item.desc}</p><div className="flex items-center gap-2 py-3.5 px-4 rounded-xl mb-6" style={{ background: 'var(--blue-subtle)', border: '1px solid rgba(21,101,242,0.15)' }}><CheckCircle2 size={16} style={{ color: 'var(--blue)', flexShrink: 0 }} /><span className="text-[14px] font-700" style={{ fontWeight: 700, color: 'var(--blue)' }}>{item.result}</span></div><div className="flex flex-wrap gap-2">{item.tech.map(tech => <span key={tech} className="text-[12px] font-600 px-2.5 py-1 rounded-lg" style={{ background: 'var(--surface-2)', color: 'var(--text-3)', fontWeight: 600 }}>{tech}</span>)}</div></motion.div>)}</div></Section></div></section>

    <section data-home-section="capabilities" className="max-w-7xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="mb-16"><p className="text-[12px] font-700 uppercase tracking-widest mb-4" style={{ color: 'var(--blue)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.homeSolutions.title}</p><h2 className="font-800 leading-tight mb-4 max-w-2xl" style={{ fontWeight: 800, fontSize: 'clamp(32px, 4vw, 44px)', letterSpacing: '-0.02em', color: 'var(--text)' }}>{t.home.outcomesTitle}</h2><p className="text-[16px] leading-relaxed max-w-xl" style={{ color: 'var(--text-3)' }}>{t.homeSolutions.sub}</p></motion.div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{t.homeSolutions.items.map((item, index) => { const Icon = SOLUTION_ICONS[index]; return <motion.a key={item.title} variants={fadeUp} whileHover={reducedMotion ? undefined : { y: -4 }} href={pagePath('solutions')} onClick={navigate('solutions')} className="ui-focus-ring p-8 rounded-2xl border transition-colors flex flex-col no-underline" style={{ background: 'var(--surface)', borderColor: 'var(--border)', textDecoration: 'none' }}><span className="w-12 h-12 rounded-xl flex items-center justify-center mb-6" style={{ background: 'var(--blue-subtle)' }}><Icon size={20} style={{ color: 'var(--blue)' }} /></span><span className="text-[18px] font-700 mb-3" style={{ fontWeight: 700, color: 'var(--text)' }}>{item.title}</span><span className="text-[14px] leading-relaxed flex-1" style={{ color: 'var(--text-3)' }}>{item.desc}</span></motion.a>; })}</div><motion.div variants={fadeUp} className="mt-12 text-center"><a href={pagePath('solutions')} onClick={navigate('solutions')} className="ui-focus-ring inline-flex items-center gap-2 text-[15px] font-700" style={{ color: 'var(--blue)', fontWeight: 700, textDecoration: 'none' }}>{t.home.capabilitiesCta}<ArrowRight size={16} /></a></motion.div></Section></section>

    <section data-home-section="process" style={{ borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)', background: 'var(--bg-2)' }}><div className="max-w-7xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="mb-16"><p className="text-[12px] font-700 uppercase tracking-widest mb-4" style={{ color: 'var(--blue)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.homeProcess.title}</p><h2 className="font-800 leading-tight max-w-xl" style={{ fontWeight: 800, fontSize: 'clamp(28px, 3.5vw, 40px)', letterSpacing: '-0.02em', color: 'var(--text)' }}>{t.homeProcess.sub}</h2></motion.div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{t.homeProcess.steps.map((step, index) => <motion.div key={step.num} variants={fadeUp} className="p-8 rounded-2xl border flex flex-col" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}><div className="flex-shrink-0 w-12 h-12 rounded-xl flex items-center justify-center text-[14px] font-800 mb-6" style={{ background: index === 0 ? 'var(--blue)' : 'var(--blue-subtle)', color: index === 0 ? '#fff' : 'var(--blue)', fontWeight: 800 }}>{step.num}</div><h3 className="text-[20px] font-700 mb-3" style={{ fontWeight: 700, color: 'var(--text)' }}>{step.title}</h3><p className="text-[15px] leading-relaxed" style={{ color: 'var(--text-3)' }}>{step.desc}</p></motion.div>)}</div></Section></div></section>

    <section data-home-section="products" className="max-w-7xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="flex flex-col sm:flex-row sm:items-end justify-between gap-6 mb-12"><div><p className="text-[12px] font-700 uppercase tracking-widest mb-4" style={{ color: 'var(--blue)', letterSpacing: '0.14em', fontWeight: 700 }}>{t.products.title}</p><h2 className="font-800 leading-tight" style={{ fontWeight: 800, fontSize: 'clamp(28px, 3.5vw, 40px)', letterSpacing: '-0.02em', color: 'var(--text)' }}>{t.products.sub}</h2></div><a href={pagePath('products')} onClick={navigate('products')} className="ui-focus-ring self-start sm:self-auto flex items-center gap-2 text-[14px] font-700" style={{ color: 'var(--blue)', fontWeight: 700, textDecoration: 'none' }}>{t.products.viewAll}<ArrowRight size={14} /></a></motion.div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{t.home.products.map(({ name, desc, status }, index) => { const Icon = PRODUCT_ICONS[index]; return <motion.a key={name} variants={fadeUp} whileHover={reducedMotion ? undefined : { y: -3 }} href={pagePath('products')} onClick={navigate('products')} className="ui-focus-ring p-6 rounded-2xl border group transition-colors no-underline" style={{ background: 'var(--surface)', borderColor: 'var(--border)', textDecoration: 'none' }}><span className="flex items-start justify-between mb-4"><span className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: 'var(--blue-subtle)' }}><Icon size={16} style={{ color: 'var(--blue)' }} /></span><span className="text-[11px] font-700 uppercase px-2.5 py-1 rounded-full" style={{ color: 'var(--text-4)', background: 'var(--surface-2)', letterSpacing: '0.06em', fontWeight: 700 }}>{status}</span></span><span className="block text-[16px] font-700 mb-2" style={{ fontWeight: 700, color: 'var(--text)' }}>{name}</span><span className="block text-[13px] leading-relaxed" style={{ color: 'var(--text-3)' }}>{desc}</span></motion.a>; })}</div></Section></section>

    <section data-home-section="faq" className="max-w-4xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="mb-12 text-center"><h2 className="font-800 leading-tight" style={{ fontWeight: 800, fontSize: 'clamp(28px, 3.5vw, 40px)', letterSpacing: '-0.02em', color: 'var(--text)' }}>{t.faq.title}</h2></motion.div><motion.div variants={fadeUp}>{t.faq.items.map(item => <FAQItem key={item.q} q={item.q} a={item.a} />)}</motion.div></Section></section>

    <section data-home-section="final-cta" className="max-w-7xl mx-auto px-6 lg:px-8 py-24 lg:py-32"><Section><motion.div variants={fadeUp} className="relative p-12 lg:p-16 rounded-2xl overflow-hidden" style={{ background: 'var(--blue)' }}><div className="absolute inset-0 pointer-events-none opacity-10" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.3) 1px, transparent 1px)', backgroundSize: '60px 60px' }} /><div className="relative text-center"><h2 className="font-800 leading-tight mb-4 text-white" style={{ fontWeight: 800, fontSize: 'clamp(28px, 4vw, 48px)', letterSpacing: '-0.02em' }}>{t.cta.title}</h2><p className="text-[17px] mb-10 text-white/80 max-w-xl mx-auto leading-relaxed">{t.cta.sub}</p><div className="flex flex-wrap justify-center gap-4"><button onClick={() => setPage('contact')} className="ui-focus-ring flex items-center gap-2 px-7 py-3.5 text-[15px] font-700 rounded-xl text-white border-white/30 transition-all" style={{ background: 'rgba(255,255,255,0.2)', fontWeight: 700, border: '1px solid rgba(255,255,255,0.3)' }}>{t.cta.btn}<ArrowRight size={15} /></button><button onClick={openAI} className="ui-focus-ring px-7 py-3.5 text-[15px] font-700 rounded-xl transition-all" style={{ background: 'rgba(0,0,0,0.2)', color: '#fff', fontWeight: 700 }}>{t.home.finalAiCta}</button></div></div></motion.div></Section></section>
  </div>;
}

function Sparkle({ size, style }: { size: number; style?: CSSProperties }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={style}><path d="M12 3L13.8 9.6L20.4 11.4L13.8 13.2L12 19.8L10.2 13.2L3.6 11.4L10.2 9.6L12 3Z" /></svg>;
}
